<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="USER-20160525XQ" ignored="0" name="test" tests="3" failures="1" timestamp="11 九月 2017 10:55:06 GMT" time="20.4" errors="0">
  <testcase name="loginSuccess" time="6.373" classname="com.witontek.ehospital2.test.LoginTest"/>
  <testcase name="loginFail" time="1.789" classname="com.witontek.ehospital2.test.LoginTest">
    <failure type="java.lang.AssertionError" message="expected [1] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [0]
	at com.witontek.ehospital2.base.AssertUtils.assertEquals(AssertUtils.java:36)
	at com.witontek.ehospital2.test.LoginTest.loginFail(LoginTest.java:35)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- loginFail -->
  <testcase name="loginFail" time="1.088" classname="com.witontek.ehospital2.test.LoginTest"/>
</testsuite> <!-- test -->
